#!/usr/bin/env python3
"""Validate handover continuity and (optionally) rebuild INDEX.md.

Checks:
- prev/next bidirectional consistency
- prev/next files exist
- only one handover has status=current
- numbering is contiguous (no gaps)

Usage:
    scripts/handover-validate.py
    scripts/handover-validate.py --rebuild-index
    scripts/handover-validate.py --strict   # exit non-zero on any issue
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required (pip install --user pyyaml)", file=sys.stderr)
    sys.exit(1)


sys.path.insert(0, str(Path(__file__).resolve().parent))
from _iris_paths import handovers_dir

HANDOVERS_DIR = handovers_dir()
INDEX_PATH = HANDOVERS_DIR / "INDEX.md"

HANDOVER_RE = re.compile(r"^handover_(\d{3})\.md$")


def split_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    return yaml.safe_load(parts[1]) or {}, parts[2]


def collect() -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for p in HANDOVERS_DIR.glob("handover_*.md"):
        m = HANDOVER_RE.match(p.name)
        if not m:
            continue
        text = p.read_text(encoding="utf-8")
        fm, _ = split_frontmatter(text)
        out.append({
            "filename": p.name,
            "number": int(m.group(1)),
            "session_id": fm.get("session_id"),
            "date": str(fm.get("date") or ""),
            "title": fm.get("title") or "",
            "prev": fm.get("prev"),
            "next": fm.get("next"),
            "status": fm.get("status"),
            "tags": fm.get("tags") or [],
        })
    out.sort(key=lambda h: h["number"])
    return out


def validate(handovers: list[dict[str, Any]]) -> list[str]:
    issues: list[str] = []
    by_name = {h["filename"]: h for h in handovers}

    # Link consistency
    for h in handovers:
        if h["prev"]:
            if h["prev"] not in by_name:
                issues.append(f"{h['filename']}: prev='{h['prev']}' missing")
            elif by_name[h["prev"]]["next"] != h["filename"]:
                issues.append(
                    f"{h['filename']}: prev points to '{h['prev']}' but '{h['prev']}'.next='{by_name[h['prev']]['next']}'"
                )
        if h["next"] and h["next"] not in by_name:
            issues.append(f"{h['filename']}: next='{h['next']}' missing")

    # Status uniqueness
    currents = [h for h in handovers if h["status"] == "current"]
    if len(currents) > 1:
        issues.append(
            f"multiple handovers marked status=current: {[c['filename'] for c in currents]}"
        )

    # Numbering contiguity
    nums = [h["number"] for h in handovers]
    if nums:
        expected = list(range(nums[0], nums[-1] + 1))
        if nums != expected:
            missing = sorted(set(expected) - set(nums))
            issues.append(f"non-contiguous numbering, missing: {missing}")

    return issues


def rebuild_index(handovers: list[dict[str, Any]]) -> None:
    lines = ["# Handover Index", ""]
    lines.append(
        "Chronological list of all handover documents. Regenerated by "
        "`scripts/handover-validate.py --rebuild-index`."
    )
    lines.append("")
    lines.append("| # | File | Date | Title | Status | Tags |")
    lines.append("|---|---|---|---|---|---|")
    for h in sorted(handovers, key=lambda x: x["number"], reverse=True):
        n = f"{h['number']:03d}"
        link = f"[{h['filename']}]({h['filename']})"
        tags = ", ".join(h["tags"][:6])
        title = h["title"] or "_(untitled)_"
        lines.append(f"| {n} | {link} | {h['date']} | {title} | {h['status'] or '—'} | {tags} |")
    lines.append("")
    lines.append("## Continuity graph")
    lines.append("")
    lines.append("```")
    chain: list[str] = []
    for h in sorted(handovers, key=lambda x: x["number"]):
        chain.append(f"handover_{h['number']:03d}")
    lines.append("  ──►  ".join(chain) + ("  ──►  (next)" if chain else ""))
    lines.append("```")
    lines.append("")
    lines.append(
        "Edit `_template.md` to change the scaffold used by "
        "`scripts/handover-new.py`."
    )
    INDEX_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rebuild-index", action="store_true")
    ap.add_argument("--strict", action="store_true", help="exit 1 on any issue")
    args = ap.parse_args()

    if not HANDOVERS_DIR.exists():
        print(f"no handovers dir at {HANDOVERS_DIR}", file=sys.stderr)
        return 1

    handovers = collect()
    issues = validate(handovers)

    print(f"checked: {len(handovers)} handover(s)")
    if issues:
        print(f"issues: {len(issues)}")
        for iss in issues:
            print(f"  • {iss}")
    else:
        print("issues: none")

    if args.rebuild_index:
        rebuild_index(handovers)
        print(f"rebuilt: {INDEX_PATH}")

    return 1 if (args.strict and issues) else 0


if __name__ == "__main__":
    sys.exit(main())
